export const APP_FEATURES = [
    {
        id : "01",
        title : "Tailored Just for You",
        description :
        "Get Interview Question and Model Answer based on Your Role , Experince , and Specific focous Area"
    },

    {
        id : "02",
        title : "Learn Your At Own Pace",
        description :
        "Expand Your Answers only when you'r ready . Dive deeper into any concept instantly with AI-Powered Answers"
    },
    
    {
        id : "03",
        title : "Capture Your Insights",
        description :
        "Add Personal Notes to any Question and pin important ones to top - malking your learning Expernice seamless"
    },

    {
        id : "04",
        title : "Undestand the Why Behind the Answers",
        description :
        "Beyond the answers - unlock detailed concpet explanation generated by AI , helping you trust the Process"
    },

    {
        id : "05",
        title : "Save , Organize And Revisit ",
        description :
        "Easily save your interview Set , organize them neatly in your dashboard and pick your preparation"
    }
]